### PR TITLE
Added New Project PC-GameInfo

### PR DESCRIPTION
**Pull request by Shashwat803**
This Project is created on the Angular framework with the help of Rapid API,
PC-GameInfo is a game info Database Application,
All the commands and packages that are needed to run this application are given in the Readme file.
this application is responsive also.
image

image

### CODE REVIEW

**Comment by Harsh3341** [comment]
Just rename your folder with your GitHub username and project name(eg- Harsh3341-NoteApp)

**Comment by Shashwat803** [comment]
I have to create a pull request again after renaming the project?

**Comment by Harsh3341** [comment]
Ya

**Comment by Shashwat803** [comment]
Please check it I renamed the project.

**Comment by Harsh3341** [comment]
Great, Thanks for contributing🎉

**Pull request merged**
